### ISSUE TITLE
`IndexError: list index out of range` when Destroying a Connection

### ISSUE THREAD

**Issue by westphaldp** [westphaldp/AVVEM#1]
When destroying a connection, the script produces `IndexError: list index out of range` and terminates without completing cleanup. Running the script again finishes the cleanup.

```
Traceback (most recent call last):
  File "./avvem.py", line 575, in <module>
    destroy(ec2_client)
  File "./avvem.py", line 548, in destroy
    i.delete()
  File "./avvem.py", line 376, in delete
    dev = [l for l in subprocess.check_output(['ip', 'address']).split('\n') if rightsourceip in l][0].split()[-1]
IndexError: list index out of range
```

**Comment by westphaldp** [comment]
I believe this was introduced because Libreswan in CentOS was leaving interfaces behind. It looks like that may have been fixed.
